# Site settings
title: Department of Procurement
email: tiffani@codeforamerica.org
description: Our mission is to model best practices in public purchasing while promoting equity, fairness and economic inclusion.
baseurl: "/atlanta-procurement-www" # the subpath of your site, e.g. /blog/
url: "http://codeforamerica.github.io" # the base hostname & protocol for your site
twitter_username: cityofatlanta
github_username:  codeforamerica

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default-with-sidenav"
  -
    scope:
      path: "opportunities"
    values:
      layout: "default-with-sidenav-shares"
      category: "solicitations"
